-- MySQL Script generated by MySQL Workbench
-- 01/10/17 22:25:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NotaApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NotaApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NotaApp` DEFAULT CHARACTER SET utf8 ;
USE `NotaApp` ;

-- -----------------------------------------------------
-- Table `NotaApp`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Periodo` (
  `id_periodo` INT NOT NULL,
  `desc_periodo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `id_anio_lectivo` INT NULL,
  PRIMARY KEY (`id_periodo`),
  INDEX `id_anio_lectivo_periodo_idx` (`id_anio_lectivo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NotaApp`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Sede` (
  `id_sede` INT NOT NULL,
  `descripcion_sede` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaApp`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Alumno` (
  `id_alumno` INT NOT NULL,
  `id_sede` INT NULL,
  `nombres` VARCHAR(45) NULL,
  `primer_apellido` VARCHAR(45) NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `desplazado` VARCHAR(45) NULL DEFAULT 'No',
  `repitente` VARCHAR(45) NULL DEFAULT 'No',
  `nombre_acudiente` VARCHAR(45) NULL,
  `apellidos_acudiente` VARCHAR(45) NULL,
  `telefono_acudiente` DOUBLE NULL,
  `fecha_matricula` DATE NULL,
  `id_grupo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_alumno`),
  INDEX `id_sede_alumno_idx` (`id_sede` ASC),
  INDEX `id_grupo_alumno_idx` (`id_grupo` ASC),
  CONSTRAINT `id_sede_alumno`
    FOREIGN KEY (`id_sede`)
    REFERENCES `NotaApp`.`Sede` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NotaApp`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Area` (
  `id_area` VARCHAR(50) NOT NULL,
  `id_sede` INT NULL,
  `nombre_area` VARCHAR(45) NULL,
  UNIQUE INDEX `id_area_UNIQUE` (`id_area` ASC),
  PRIMARY KEY (`id_area`),
  INDEX `id_sede_area_idx` (`id_sede` ASC),
  CONSTRAINT `id_sede_area`
    FOREIGN KEY (`id_sede`)
    REFERENCES `NotaApp`.`Sede` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NotaApp`.`Tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL,
  `des_tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaApp`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Docente` (
  `id_docente` INT NOT NULL,
  `id_tipo_usuario` INT NULL,
  `nombres` VARCHAR(45) NULL,
  `prim_apellido` VARCHAR(45) NULL,
  `seg_apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(128) NULL,
  `id_sede` INT NULL,
  PRIMARY KEY (`id_docente`),
  INDEX `id_tipo_usuario_idx` (`id_tipo_usuario` ASC),
  INDEX `id_sede_usuario_idx` (`id_sede` ASC),
  CONSTRAINT `id_tipo_usuario`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `NotaApp`.`Tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_sede_usuario`
    FOREIGN KEY (`id_sede`)
    REFERENCES `NotaApp`.`Sede` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NotaApp`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Grado` (
  `id_grado` VARCHAR(50) NOT NULL,
  `id_sede` INT NULL,
  `descripcion_grado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grado`),
  INDEX `id_sede_grado_idx` (`id_sede` ASC),
  CONSTRAINT `id_sede_grado`
    FOREIGN KEY (`id_sede`)
    REFERENCES `NotaApp`.`Sede` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NotaApp`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Asignatura` (
  `id_asignatura` VARCHAR(50) NOT NULL,
  `id_docente` INT NULL,
  `id_area` VARCHAR(50) NULL,
  `nombre_asignatura` VARCHAR(45) NULL,
  `intensidad_horaria` INT NULL,
  PRIMARY KEY (`id_asignatura`),
  INDEX `id_docente_idx` (`id_docente` ASC),
  INDEX `id_area_asignatura_idx` (`id_area` ASC),
  CONSTRAINT `id_docente_asig`
    FOREIGN KEY (`id_docente`)
    REFERENCES `NotaApp`.`Docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_area_asig`
    FOREIGN KEY (`id_area`)
    REFERENCES `NotaApp`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NotaApp`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Grupo` (
  `id_grupo` VARCHAR(50) NOT NULL,
  `id_grado` VARCHAR(50) NULL,
  `id_docente` INT NULL,
  `descripcion_grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `id_grado_grupo_idx` (`id_grado` ASC),
  INDEX `id_docente_grupo_idx` (`id_docente` ASC),
  CONSTRAINT `id_grado_grupo`
    FOREIGN KEY (`id_grado`)
    REFERENCES `NotaApp`.`Grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_docente_grupo`
    FOREIGN KEY (`id_docente`)
    REFERENCES `NotaApp`.`Docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NotaApp`.`Logros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Logros` (
  `id_periodo` INT NULL,
  `id_grupo` VARCHAR(50) NULL,
  `id_asignatura` VARCHAR(50) NULL,
  `descripcion` VARCHAR(255) NULL,
  INDEX `id_periodo_logros_idx` (`id_periodo` ASC),
  INDEX `id_grupo_logros_idx` (`id_grupo` ASC),
  INDEX `id_asignatura_logros_idx` (`id_asignatura` ASC),
  CONSTRAINT `id_periodo_logros`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `NotaApp`.`Periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupo_logros`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `NotaApp`.`Grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_asignatura_logros`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `NotaApp`.`Asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaApp`.`Anio_Lectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Anio_Lectivo` (
  `id_anio_lectivo` INT NULL,
  `id_sede` INT NULL,
  `descripcion_anio_lectivo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  UNIQUE INDEX `id_Anio_Lectivo_UNIQUE` (`id_anio_lectivo` ASC),
  INDEX `id_sede_anio_lestivo_idx` (`id_sede` ASC),
  CONSTRAINT `id_sede_anio_lectivo`
    FOREIGN KEY (`id_sede`)
    REFERENCES `NotaApp`.`Sede` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaApp`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Asistencia` (
  `id_alumno` INT NOT NULL,
  `id_asignatura` VARCHAR(50) NULL,
  `id_periodo` INT NULL,
  `inasistencia` INT NULL,
  PRIMARY KEY (`id_alumno`),
  INDEX `id_asignatura_asistencia_idx` (`id_asignatura` ASC),
  INDEX `id_periodo_idx` (`id_periodo` ASC),
  CONSTRAINT `id_alumno_asis`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `NotaApp`.`Alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_asignatura_asis`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `NotaApp`.`Asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_periodo`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `NotaApp`.`Periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaApp`.`Nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Nota` (
  `id_alumno` INT NOT NULL,
  `id_anio_lectivo` INT NULL,
  `id_periodo` INT NULL,
  `id_grupo` VARCHAR(50) NULL,
  `nota` DECIMAL(20) NULL,
  PRIMARY KEY (`id_alumno`),
  INDEX `id_periodo_nota_idx` (`id_periodo` ASC),
  INDEX `id_grupo_nota_idx` (`id_grupo` ASC),
  CONSTRAINT `id_alumno_nota`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `NotaApp`.`Alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_periodo_nota`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `NotaApp`.`Periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupo_nota`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `NotaApp`.`Grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaApp`.`Nota_Definitiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaApp`.`Nota_Definitiva` (
  `id_alumno` INT NOT NULL,
  `id_area` VARCHAR(50) NULL,
  `id_anio_lectivo` INT NULL,
  `nota_definitiva` DECIMAL(20) NULL,
  PRIMARY KEY (`id_alumno`),
  INDEX `id_area_notadef_idx` (`id_area` ASC),
  INDEX `id_anio_lectivo_notadef_idx` (`id_anio_lectivo` ASC),
  CONSTRAINT `id_alumno_notadef`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `NotaApp`.`Alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_area_notadef`
    FOREIGN KEY (`id_area`)
    REFERENCES `NotaApp`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_anio_lectivo_notadef`
    FOREIGN KEY (`id_anio_lectivo`)
    REFERENCES `NotaApp`.`Anio_Lectivo` (`id_anio_lectivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `NotaApp`.`Sede`
-- -----------------------------------------------------
START TRANSACTION;
USE `NotaApp`;
INSERT INTO `NotaApp`.`Sede` (`id_sede`, `descripcion_sede`) VALUES (1, 'Instituto Estrada');

COMMIT;


-- -----------------------------------------------------
-- Data for table `NotaApp`.`Tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `NotaApp`;
INSERT INTO `NotaApp`.`Tipo_usuario` (`id_tipo_usuario`, `des_tipo_usuario`) VALUES (1, 'Root');
INSERT INTO `NotaApp`.`Tipo_usuario` (`id_tipo_usuario`, `des_tipo_usuario`) VALUES (2, 'Administrador');
INSERT INTO `NotaApp`.`Tipo_usuario` (`id_tipo_usuario`, `des_tipo_usuario`) VALUES (3, 'Docente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `NotaApp`.`Docente`
-- -----------------------------------------------------
START TRANSACTION;
USE `NotaApp`;
INSERT INTO `NotaApp`.`Docente` (`id_docente`, `id_tipo_usuario`, `nombres`, `prim_apellido`, `seg_apellido`, `email`, `pass`, `id_sede`) VALUES (654321, 2, 'Administrador', 'Admin', 'Admin2', 'admin@admin.com', '$2y$10$sSYgkIxAGpIiE.PfYRb1EuVFgJCr/envp28P4iDmwB2N4/2Rp7uOW', 1);

COMMIT;

